name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t manczaknet .
      - name: Run image
        run: |
          docker stop manczaknet || true
          docker rm manczaknet || true
          docker run -d -p 3000:3000 --name manczaknet --restart always manczaknet
